name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      # - name: Generate metadata
      #   run: cargo install subxt-cli && subxt metadata -f bytes > polkadot.scale

      - name: Install .env .keyfile
        run: cp .env.example .env && cp .keyfile.example .keyfile

      - name: Build binary
        run: cargo build --release

      - name: Rename binary
        run: mv target/release/paypig paypig-x86_64

      - name: Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          make_latest: true
          files: paypig-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
