# .github/workflows/release.yml
name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: rust-lang/setup-rust@v1
        with:
          rust-version: stable
          targets: x86_64-unknown-linux-gnu

      - name: Generate metadata
        run: cargo install subxt-cli && subxt metadata -f bytes > polkadot.scale

      - name: Build binary
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Add architechture in binary name
        run: mv target/x86_64-unknown-linux-gnu/release/paypig paypig-x86_64

      - name: Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          files: paypig-x86_64
